author = "Keichi Takahashi"
description = "Simple and clean blog theme for hugo"
license = "MIT"
name = "vienna"
source_repo = "https://github.com/matthewbentley/vienna.git"
tags = ["blog", "tags", "bootstrap"]
